apiVersion: v1
kind: ConfigMap
metadata:
  name: __APPNAME__-config

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: __APPNAME__-deployment
  labels:
    app: __APPNAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __APPNAME__
  template:
    metadata:
      labels:
        app: __APPNAME__
    spec:
      imagePullSecrets:
        - name: docker-reg-secret   
      containers:
      - name: __APPNAME__
        image: __PROD_IMAGE__
        envFrom:
        - configMapRef:
            name: __APPNAME__-config        
        ports:
        - containerPort: 80
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: __APPNAME__
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: __APPNAME__
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 80m
  name: __APPNAME__
spec:
  rules:
    - host: sars.skio.cn
      http:
        paths:
          - backend:
              serviceName: __APPNAME__
              servicePort: 80
            path: /
  tls:
    - hosts:
        - sars.skio.cn
      secretName: skio.cn
